name: ETL Pipeline Demo

on:
  push:
    branches:
      - main

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Install pandas
        run: pip install -r requirements.txt

      - name: Run extract.py
        run: python extract.py